version: "3.9"

services:
  app:
    container_name: klyp-go-app
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .default.env
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: klyp-yugabytedb
    image: yugabytedb/yugabyte:2.25.2.0-b359
    restart: always
    command: >
      bin/yugabyted start
      --background=false
      --daemon=false
    ports:
      - "5433:5433"
      - "7000:7000"
      - "9000:9000"
      - "15433:15433"
    environment:
      YSQL_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "bin/yugabyted status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s